import localFont from "next/font/local";
import "./globals.css";
import ClientProvider from "./ClientProvider"; // کامپوننت کلاینتی
import { JSX, ReactNode } from "react";

// تعریف فونت‌ها
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// تعریف متادیتا
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// تعریف نوع برای props
interface RootLayoutProps {
  children: ReactNode;
}

// کامپوننت RootLayout
export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
