import localFont from "next/font/local";
import "./globals.css";
import ClientProvider from "./ClientProvider"; // کامپوننت کلاینتی
import { JSX, ReactNode } from "react";

// تعریف فونت از فولدر public
const IRANSans = localFont({
  src: "/fonts/IRANSansWeb.woff", // مسیر به فایل داخل public
  variable: "--font-iran-sans",
  weight: "100 900",
});

// تعریف متادیتا
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// تعریف نوع برای props
interface RootLayoutProps {
  children: ReactNode;
}

// کامپوننت RootLayout
export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html dir="rtl" lang="fa">
      <body className={`${IRANSans.variable} antialiased bg-gray-50`}>
        <ClientProvider>
          {children}
          </ClientProvider>
      </body>
    </html>
  );
}
